### ISSUE TITLE
Support for FreeBSD

### ISSUE THREAD

**Issue by misullivan** [thias/puppet-squid3#11]
Support for FreeBSD should be trivial by the looks of it.

Here's the relevant paths (pulled from 2.7 - the paths where relevant are the same for 3.x) if you wouldn't mind adding support:

Config file: /usr/local/etc/squid/squid.conf
cache_dir: /var/squid/cache 
access_log: /var/squid/logs/access.log
cache_log: /var/squid/logs/cache.log
cache_store_log: /var/squid/logs/store.log
pid_filename: /var/squid/logs/squid.pid
netdb_filename: /var/squid/logs/netdb.state
coredump_dir: /var/squid/cache

**Comment by thias** [comment]
Added in 134ab076148d369a7556401f70d57954bafda0ea.
