### ISSUE TITLE
Fix hardcoded coredump_dir value in template. 

### ISSUE THREAD

**Issue by wunzeco** [thias/puppet-squid3#18]
The value of coredump_dir in squid.conf.short.erb is hardcoded as "/var/spool/squid" which is incorrect for Debian-family operating system. So instead use 

```
coredump_dir                               <%= @coredump_dir %>
```

**Comment by thias** [comment]
Fixed in ab48c78d2bce0a318f99de4529bba4ea26564137. Thanks!
