### ISSUE TITLE
Error: Execution of '/usr/sbin/update-rc.d squid3 defaults' returned 1: update-rc.d: /etc/init.d/squid3: file does not exist

### ISSUE THREAD

**Issue by ppouliot** [thias/puppet-squid3#22]
The following occurs when applying the module on Ubuntu 14.04.

Debug: Executing '/usr/sbin/update-rc.d squid3 defaults'
Error: Execution of '/usr/sbin/update-rc.d squid3 defaults' returned 1: update-rc.d: /etc/init.d/squid3: file does not exist

This occurs on Ubuntu 14.04.

**Comment by jurgenweber** [comment]
yeah, the service definition is broken.

https://github.com/thias/puppet-squid3/blob/master/manifests/init.pp#L62-L70

**Comment by thias** [comment]
This is probably an upstart+puppet problem, see #14.
